lab2 individual variant
sergey-berezin/441_2_vodyanyj pull request #3
Opened 2023-11-12 15:08 UTC by andrey-voter

2023-11-14 08:23 UTC, sergey-berezin commented
Для сдачи второго задания вам нужно прийти на занятие по технологической практике и показать работающую программу.

2023-11-24 18:20 UTC, andrey-voter commented
Добрый вечер! Добавил третью лабораторную работу (случайно получилось 2 коммита). Т. к. предыдущий пул реквест был не закрыт, то коммит, относящийся к 3 лабораторной попал сюда

2023-11-26 13:38 UTC, sergey-berezin requested changes

2023-11-26 13:38 UTC, sergey-berezin commented on Task2/Task2/MainWindow.xaml.cs
> +            DialogEntry? savedEntry = history.Entries.FirstOrDefault(entry => entry.Question == question_text);
Что если один вопрос задавался по нескольким текстам? Для какого текста будет выдан ответ?

2023-11-27 10:00 UTC, merged